<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Readify.Infrastructure</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="EpubSharp.dll"/>
        <PackageReference Include="SixLabors.ImageSharp"/>
        <PackageReference Include="TorchSharp"/>
        <PackageReference Include="TorchSharp-cpu"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ReadifyAI.Application\ReadifyAI.Application.csproj"/>
        <ProjectReference Include="..\ReadifyAI.Core\ReadifyAI.Core.csproj"/>
    </ItemGroup>

</Project>
